package org.javacs.kt.diagnostic

internal const val STRUCTURAL_DIAGNOSTIC_SOURCE = "kotlin-structural"

internal const val STRUCTURAL_INCOMPLETE_EXPRESSION = "STRUCTURAL_INCOMPLETE_EXPRESSION"
internal const val STRUCTURAL_INCOMPLETE_FUNCTION_BODY = "STRUCTURAL_INCOMPLETE_FUNCTION_BODY"
internal const val STRUCTURAL_MISMATCHED_DELIMITER = "STRUCTURAL_MISMATCHED_DELIMITER"
internal const val STRUCTURAL_UNCLOSED_DELIMITER = "STRUCTURAL_UNCLOSED_DELIMITER"
internal const val STRUCTURAL_UNMATCHED_CLOSING = "STRUCTURAL_UNMATCHED_CLOSING"
internal const val STRUCTURAL_UNTERMINATED_BACKTICK_IDENTIFIER = "STRUCTURAL_UNTERMINATED_BACKTICK_IDENTIFIER"
internal const val STRUCTURAL_UNTERMINATED_BLOCK_COMMENT = "STRUCTURAL_UNTERMINATED_BLOCK_COMMENT"
internal const val STRUCTURAL_UNTERMINATED_CHAR_LITERAL = "STRUCTURAL_UNTERMINATED_CHAR_LITERAL"
internal const val STRUCTURAL_UNTERMINATED_RAW_STRING_LITERAL = "STRUCTURAL_UNTERMINATED_RAW_STRING_LITERAL"
internal const val STRUCTURAL_UNTERMINATED_STRING_LITERAL = "STRUCTURAL_UNTERMINATED_STRING_LITERAL"
