name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['11', '17']
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: .\gradlew.bat :server:build :shared:build -PjavaVersion=${{ matrix.java }}
      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: ./gradlew :server:build :shared:build -PjavaVersion=${{ matrix.java }}
      - name: Detekt (Windows)
        if: runner.os == 'Windows'
        run: .\gradlew.bat detekt -PjavaVersion=${{ matrix.java }}
      - name: Detekt (Unix)
        if: runner.os != 'Windows'
        run: ./gradlew detekt -PjavaVersion=${{ matrix.java }}
